# Generated by Django 5.2.3 on 2025-07-15 18:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('code_project', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('content', models.TextField()),
                ('coordinator', models.CharField(max_length=30)),
                ('investor', models.CharField(max_length=30)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('development', models.CharField(choices=[('building permit', 'Building permit'), ('protocol 2', 'Protocol 2'), ('order book', 'Order Book'), ('act 10', 'ACT 10'), ('act 11', 'ACT 11'), ('statutory act 15', 'Statutory Act 15'), ('protokol 17', 'Protocol 17'), ('protokol 16', 'Protocol 16'), ('permission usage', 'Permission Usage')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
