# Generated by Django 5.2.3 on 2025-07-20 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code_project',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
