# Generated by Django 5.2.3 on 2025-07-15 18:32

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=110, unique=True, validators=[django.core.validators.MinLengthValidator(2), core.validators.validate_name])),
                ('permit', models.CharField(max_length=30)),
                ('contract', models.CharField(max_length=30)),
                ('budged', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[core.validators.validator_phone])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('document', models.FileField(upload_to='builder_documents', validators=[core.validators.SizeValidator(5)])),
                ('project', models.ManyToManyField(related_name='builders', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
